ALTER TABLE subscriptions
ADD COLUMN IF NOT EXISTS razorpay_subscription_id VARCHAR(64) NULL,
ADD COLUMN IF NOT EXISTS razorpay_customer_id VARCHAR(64) NULL,
ADD COLUMN IF NOT EXISTS auth_payment_id VARCHAR(64) NULL,
ADD COLUMN IF NOT EXISTS current_period_start DATETIME NULL,
ADD COLUMN IF NOT EXISTS current_period_end DATETIME NULL,
ADD COLUMN IF NOT EXISTS next_charge_at DATETIME NULL,
ADD COLUMN IF NOT EXISTS total_count INT NULL,
ADD COLUMN IF NOT EXISTS paid_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS cancel_at_period_end TINYINT(1) NOT NULL DEFAULT 0;
